### PR TITLE
Fixed sexp-cli documentation

### LINKED ISSUE #9: `sexp-cli` help command showing wrong executable name
```
$ sexp-cli -h
The program `sexp' reads, parses, and prints out S-expressions.
...
```

Clearly the executable name now is called `sexp-cli`, not `sexp`. We need to decide whether:
* the executable name should actually be `sexp`
* or the help output should show `sexp-cli`.

We are also missing documentation and examples on how to use `sexp-cli`:
```
 INPUT:
   Input is normally taken from stdin, but this can be changed:
      -i filename      -- takes input from file instead.
      -p               -- prompts user for console input
   Input is normally parsed, but this can be changed:
      -s               -- treat input up to EOF as a single string
 CONTROL LOOP:
   The main routine typically reads one S-expression, prints it out again, 
   and stops.  This may be modified:
      -x               -- execute main loop repeatedly until EOF
 OUTPUT:
   Output is normally written to stdout, but this can be changed:
      -o filename      -- write output to file instead
   The output format is normally canonical, but this can be changed:
      -a               -- write output in advanced transport format
      -b               -- write output in base-64 output format
      -c               -- write output in canonical format
      -l               -- suppress linefeeds after output
   More than one output format can be requested at once.
 There is normally a line-width of 75 on output, but:
      -w width         -- changes line width to specified width.
                          (0 implies no line-width constraint)
 The default switches are: -p -a -b -c -x
 Typical usage: cat certificate-file | sexp -a -x 
```

### PR DESCRIPTION
**Pull request by maxirmx**

### CODE REVIEW

**Comment by ronaldtse** [comment]
Thanks @maxirmx . Question: why not just use “sexp” instead of “sexp-cli”?  If it’s accessible via the CLI, it is a cli command…

**Comment by maxirmx** [comment]
> Thanks @maxirmx . Question: why not just use “sexp” instead of “sexp-cli”? If it’s accessible via the CLI, it is a cli command…

In cmake script both ```libsexp.a``` and ```sexp``` will have logical name ```sexp```, that's why I cut the corner.  I will rename the application to ```sexp```, it;s doable.

**Comment by ronaldtse** [comment]
Thank you @maxirmx !

**Review by ronaldtse — APPROVED** [review]

**Comment by ronaldtse** [comment]
@maxirmx can we have a version bump? Thanks!

**Pull request merged**
