### PR TITLE
RNP integration

### LINKED ISSUE #1: Create a CMake-importable library for creating/parsing SEXP
The reference implementation is at:
https://people.csail.mit.edu/rivest/sexp.html

We must also wrap this with tests as provided:

> Here are some sample inputs and outputs (warning: while these look like SDSI/SPKI files, they are only approximations).
> 
> [canonical](https://people.csail.mit.edu/rivest/sexp-sample-c)
> [transport](https://people.csail.mit.edu/rivest/sexp-sample-b)
> [advanced](https://people.csail.mit.edu/rivest/sexp-sample-a)

### LINKED ISSUE #7: Add nix flake support

### LINKED ISSUE #8: Make download of googletests optional
Some package building environments do not have access to Internet (e.g. Nix), meaning this will not build in those environments.

For reference, this is how it is done in RNP (but without version specification): https://github.com/rnpgp/rnp/commit/bc4567bdcca7d4d1b1018c13541913a3fc30e274

Related: https://github.com/rnpgp/rnp/pull/1943#issuecomment-1315328258

### PR DESCRIPTION
**Pull request by maxirmx**

### CODE REVIEW

**Comment by maxirmx** [comment]
Although it is a pull request this code is really version 1
Genesys:
K&R C reference implementation of 1997 was rewritten 3 or 4 times to become C++ code while keeping compatibility with original samples and output.   After that several functions were added in order to simplify rap integration.

**Comment by ribose-jeffreylau** [comment]
@maxirmx Thanks for the Nix integration!  Did not expect it to be implemented here in this PR.

There is some slight problem -- the Nix formula, although it builds, it currently does not produce any outputs (the Nix output directory `result/` is empty after a `nix build`).  I'm OK to deal with Nix in a separate PR so it would not block the rest of this PR.  What do you think?

**Comment by ronaldtse** [comment]
> I'm OK to deal with Nix in a separate PR so it would not block the rest of this PR. What do you think?

Agree, let's deal with it in a new PR. Let's merge this first. Thanks!

**Review by ronaldtse — APPROVED** [review]
Thank you @maxirmx !

**Pull request merged**
